// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e37fc19ad42a8f945696ea2e1b76a981a492ea2e/koa-compose/index.d.ts
declare module 'koa-compose' {
// Type definitions for koa-compose 3.2
// Project: https://github.com/koajs/compose
// Definitions by: jKey Lu <https://github.com/jkeylu>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


function compose<T>(middleware: Array<compose.Middleware<T>>): compose.ComposedMiddleware<T>;

namespace compose {
    type Middleware<T> = (context: T, next: () => Promise<any>) => any;
    type ComposedMiddleware<T> = (context: T, next?: () => Promise<any>) => Promise<void>;
}

export = compose;
}
